<?php
/**
 * @file
 * Way2SMS Module Implementation.
 */

/**
 * Implements hook_help().
 */
function way2sms_help($path, $arg) {
  switch ($path) {
    case 'admin/help#way2sms':
      $output = file_get_contents(drupal_get_path('module', 'Way2SMS') . '/README.md');
      return module_exists('markdown') ? filter_xss_admin(module_invoke('markdown', 'filter', 'process', 0, -1, $output)) : '<pre>' . check_plain($output) . '</pre>';
  }
}

/**
 * Implements hook_menu().
 */
function way2sms_menu() {
  $items['admin/config/services/way2sms'] = array(
    'title' => 'Way2SMS Configuration',
    'description' => "Way2SMS Configuration for Sender's so as to use it to send message through Way2SMS API.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('way2sms_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'way2sms.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
